[versions]
accompanistDrawablepainter = "0.37.3"
agp = "8.12.3"
appcompat = "1.7.1"
audienceNetworkSdk = "6.20.0"
googleAdsMediationFacebook = "6.20.0.2"
billingKtx = "8.0.0"
composeBomVersion = "2025.10.01"
constraintlayout = "2.2.1"
converterGson = "3.0.0"
coreKtxVersion = "1.7.0"
databindingRuntime = "8.13.0"
firebaseAds = "23.6.0"
firebaseCore = "21.1.1"
fragmentKtx = "1.8.9"
inferAnnotation = "0.18.0"
coreKtx = "1.17.0"
inmobi = "10.8.8.1"
inmobiAdsKotlin = "11.0.0"
mediationsdk = "9.0.0"
ironsource = "9.0.0.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesCore = "1.10.2"
kotlinxCoroutinesTest = "1.10.2"
legacySupportV4 = "1.0.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
mockitoCore = "5.20.0"
multidex = "2.0.1"
playServicesAds = "24.7.0"
recyclerview = "1.4.0"
retrofit = "3.0.0"
robolectric = "4.16"
truth = "1.7.0"
uiautomator = "2.3.0"
roomRuntime = "2.8.3"
roomCommonJvm = "2.8.3"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanistDrawablepainter" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-databinding-runtime = { module = "androidx.databinding:databinding-runtime", version.ref = "databindingRuntime" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomRuntime" }
androidx-room-common-jvm = { module = "androidx.room:room-common-jvm", version.ref = "roomCommonJvm" }
androidx-rules = { module = "androidx.test:rules", version.ref = "coreKtxVersion" }
androidx-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-truth = { module = "androidx.test.ext:truth", version.ref = "truth" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
audience-network-sdk = { module = "com.facebook.android:audience-network-sdk", version.ref = "audienceNetworkSdk" }
google-ads-mediation-facebook = { module = "com.google.ads.mediation:facebook", version.ref = "googleAdsMediationFacebook"}
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtxVersion" }
firebase-ads = { module = "com.google.firebase:firebase-ads", version.ref = "firebaseAds" }
firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebaseCore" }
infer-annotation = { module = "com.facebook.infer.annotation:infer-annotation", version.ref = "inferAnnotation" }
inmobi-ads-kotlin-sdk = { module = "com.inmobi.monetization:inmobi-ads-kotlin", version.ref = "inmobiAdsKotlin" }
google-ads-mediation-inmobi = { module = "com.google.ads.mediation:inmobi", version.ref = "inmobi" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
#noinspection SimilarGradleDependency
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBomVersion" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
ironsource-mediation-sdk = { module = "com.unity3d.ads-mediation:mediation-sdk", version.ref = "mediationsdk" }
google-ads-mediation-ironsource = { module = "com.google.ads.mediation:ironsource", version.ref = "ironsource" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.2.21" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version = "2.2.21" }

